/*
 * Copyright (c) 2019. Dmitriy Kargashin
 */

package com.dmitriykargashin.cardamontimecalculator.engine.calculator

val MILLISECONDS_IN_SECOND = 1000.toBigDecimal()
val SECONDS_IN_MINUTE = 60.toBigDecimal()
val MINUTES_IN_HOUR = 60.toBigDecimal()
val HOURS_IN_DAY = 24.toBigDecimal()
val DAYS_IN_WEEK = 7.toBigDecimal()
val DAYS_IN_MONTH = 30.toBigDecimal()
val DAYS_IN_YEAR = 365.toBigDecimal()

val MILLISECONDS_IN_YEAR =
    MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE * MINUTES_IN_HOUR * HOURS_IN_DAY * DAYS_IN_YEAR

val MILLISECONDS_IN_MONTH =
    MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE * MINUTES_IN_HOUR * HOURS_IN_DAY * DAYS_IN_MONTH

val MILLISECONDS_IN_WEEK =
    MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE * MINUTES_IN_HOUR * HOURS_IN_DAY * DAYS_IN_WEEK

val MILLISECONDS_IN_DAY =
    MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE * MINUTES_IN_HOUR * HOURS_IN_DAY

val MILLISECONDS_IN_HOUR =
    MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE * MINUTES_IN_HOUR

val MILLISECONDS_IN_MINUTE =
    MILLISECONDS_IN_SECOND * SECONDS_IN_MINUTE